version: "3.9"

services:
  api:
    build: ./api
    container_name: api
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_DRIVER=${DATABASE_DRIVER}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - database

  database:
    image: postgres:14.2-alpine
    container_name: database
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - user-cms:/var/lib/postgresql/data/
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5050:80
    restart: always

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./migrations:/database
    command: -path /database -database postgres://olafsz:FCbarca123@database:5432/users?sslmode=disable up
    depends_on:
      - database

volumes:
  user-cms: