version: "3.9"

services:
  api:
    build: ./api
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    depends_on:
      - database

  database:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD=md5
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - user-cms:/var/lib/postgresql/data/
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 5050:80
    restart: always
      
volumes:
  user-cms:  