ALTER TABLE users DROP COLUMN username;
ALTER TABLE users DROP COLUMN email;
ALTER TABLE users ADD COLUMN username VARCHAR(30) NOT NULL UNIQUE;
ALTER TABLE users ADD COLUMN email VARCHAR(80) NOT NULL UNIQUE;